### ISSUE TITLE
Badge only shows the first 3 digits of the Tab-Count

### ISSUE THREAD

**Issue by clerie** [DaAwesomeP/tab-counter#28]
The badge in my status-bar only shows the first 3 digits of the tab-count. I expect to see the full count.
I use Firefox 72 on Ubuntu.

![](https://user-images.githubusercontent.com/9381848/73844999-fa60f400-4821-11ea-9b20-0b572a3aeb03.png)

**Comment by Smile4ever** [comment]
This is a limitation of Firefox. Using the "K" notation like "1,3K" could work, but is not 100% accurate and might also not fit into the browserAction (button) tooltip.

**Comment by DaAwesomeP** [comment]
@Smile4ever is correct—there is a size limitation. I do not recall if the limitation is width- or character count-based, but I definitely encountered it and worked around it as best I could. I would accept a pull for a notation like "1,3K" if and only if it never cuts off the K.

Closing since this is an extensions API limitation.
