### ISSUE TITLE
0.1.0 not automatically updated

### ISSUE THREAD

**Issue by grahamperrin** [DaAwesomeP/tab-counter#9]
From `about:support`:

```text
    {
      "name": "Tab Counter",
      "version": "0.1.0",
      "isActive": false,
      "id": "tab-counter@daawesomep.addons.mozilla.org"
    },
```

I can uninstall, then reinstall a more recent version, but I'm puzzled by there being no detection of updates.

**Comment by DaAwesomeP** [comment]
I'm not sure why you weren't updated automatically. I do not implement the update mechanism; Mozilla handles all of that. Please check that your extensions are set to automatically update or that the update setting on the addon settings page is set to "on."

**Comment by grahamperrin** [comment]
Thanks. I tried with a clean profile with 0.1.0, 0.1.1 and 0.2.0, Firefox 56.0.2 (64-bit) on FreeBSD-CURRENT. None of the three automatically updates to 0.2.1.

**Comment by DaAwesomeP** [comment]
This really puzzles me. You should open an issue on the Mozilla bug tracker. The only thing that comes to mind is that when uploading the extension, it asks what platforms that it is compatible with. The options are Windows, Mac, Linux, and Android. I check everything but Android. Maybe they classify Linux and BSD separately in the update process but not the initial install process. (technically they should separate that everywhere but I can see why not).

Unfortunately, the addon author doesn't control the update or install mechanisms. I'm going to close this since I can't see any way for me to fix it on the extension end. Please feel free to continue discussion here. You can watch this repo on GitHub to get an email notification when I make changes.
